# Generated by Django 3.1 on 2024-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='images',
            field=models.FileField(upload_to='image'),
        ),
    ]
